project:
  type: website
  output-dir: docs
  resources:
    - valfredda2D.mp4

website:
  title: "Laura Moreno Martínez"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - cv.qmd  
      - research.qmd  
      - publications.qmd
      - presentations.qmd
      - teaching.qmd
      - blog.qmd
  google-analytics: G-67M1JQ9KKG

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



