project:
  type: website
  output-dir: docs
  resources:
    - valfredda2D.mp4

website:
  title: "Laura Moreno Martínez"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - cv.qmd  
      - text: Research
        menu:
          - href: research.qmd
            text: Research overview
          - href: projects.qmd
            text: Projects
      - publications.qmd
      - presentations.qmd
      - teaching.qmd
      - href: blog.qmd
        text: News
  google-analytics: G-67M1JQ9KKG

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

