---
title: "Curriculum Vitae"
---

[[Download here my cv in pdf](/assets/docs/cv_laura_2501.pdf)]

## Experience
**Assistant Professor** (01/09/2024 - present)\
Department of Applied Mathematics, University of Alicante, Spain

**Post-doctoral researcher** (18/09/2023 - 31/08/2024)\
Institut für Statik un Dynamik, Technical University of Braunschweig, Germany\
Supervisor: Prof. [Roland Wuechner](https://www.cee.ed.tum.de/st/mitarbeiterinnen/roland-wuechner/)\
*Developing particle techniques to model the constitutional evolution of building materials and structures with respect to aging.*

**Post-doctoral researcher** (01/10/2021 - 14/09/2023)\
Department of Mathematics ”Tullio Levi Civita”, Università degli Studi di Padova, Italy\
Supervisor: Prof. [Antonia Larese](https://www.math.unipd.it/~antonia/)\
*Studying and implementing Full Order Models using finite elements and particle techniques for multiphysics coupled simulations.*

**Pre-doctoral researcher** (01/09/2016 - 22/09/2021)\
CIMNE, Universitat Politècnica de Catalunya, Barcelona, Spain\
Supervisor: Prof. Ramon Codina and Prof. Joan Baiges\
*Developing mathematical and numerical methods to simulate viscoelastic fluid flows with high elasticity in a finite element framework, including thermal effects. These models are implemented in a high-performance computing environment using object-oriented Fortran.*

**Solutions Assistant (SA-N1)** (01/12/2015 - 31/08/2016)\
EVERIS, Barcelona, Spain\
*Providing technical support for a high-tech database system.*

**Research Assistant** (01/09/2014 - 28/02/2015)\
Department of Applied Mathematics, Unidersidade de Santiago de Compostela, Santiago de
Compostela, Spain\
*Studying and numerically simulating electromagnetic processes with hysteresis*

## Education
**Doctor of Philosophy (Ph.D.) in Structural Analysis** (01/09/2016 - 22/09/2021)\
Department of Civil Engineering, Universitat Politècnica de Catalunya, Barcelona, Spain\
<u>Title</u>: *Numerical modelling of viscoelastic flows based on a log-conformation formulation*. [[Link](https://www.tdx.cat/handle/10803/672679#page=1)]\
<u>Supervisors</u>: Prof. [Ramon Codina](https://deca.upc.edu/en/people/ramon.codina) i Rovira and Prof. [Joan Baiges](https://sites.google.com/site/joanbaiges/home).\
<u>Qualification</u>: Excellent cum laude.

**M.Sc. Industrial Mathematics** (01/09/2013 - 25/07/2015)\
Department of Applied Mathematics, Universidade de Santiago de Compostela, Spain\
<u>Title Mater's thesis</u>: *Simulación magnetohidrodinámica del efecto de elevació de una columna de metal fundido con una máquina de inducción lineal.* \
<u>Supervisors</u>: Alfredo Bermúdez de Castro.\
<u>Qualification</u>: 10/10.

**M.Sc. Mathematics** (01/09/2008 - 05/07/2013)\
Faculty of science, Universidad de Alicante, Spain

## Fellowships and awards
* Post-doc vacancy awarded at Resarch Training Group GRK 2075\2

* Post-doc fellowship awarded at UNIPD, 01/10/2021

* PhD thesis mark with honors (Excellent Cum Laude), 22/09/2021

* 4-years Spanish government PhD scholarship. FPI: DPI2015-67857-R, 18/04/2017

## Participation in research projects

### National and International projects

- **GRK 2075**. ( Research Training Group) Modelling the constitutional evolution of building materials and structures with respect to aging.\
Funding by German Research Foundation.\
Participation: 18/10/2023 to 30/09/2024.

- **REACT** Digital Twins Of Civil StRucturEs And Protection Systems In A ClimAte Change PerspecTive.\
PI: Antonia Larese.(80.000€)\
Founded by: TUM-IAS, Munich, Germany. \
From 01/10/2021 to 30/09/2024.\
Participation: 01/10/2022 to 15/09/2023

- **SID2020-NEMESIS.** NumErical MEthods for the SImulation of the impact of extreme hazards on Structures and landscape.\
Founded by: University of Padova. (39.376,70 €)\
PI: Antonia Larese \
From 18/11/2020 to 31/12/2022\
Participation: 01/10/2021 to 15/09/2023

- **ELASTIC-FLOW.** Aumento de la eficiencia en procesos de mezcla y transmisión de calor utilizando fluidos viscoelásticos en régimen laminar y turbulento.\
Funded by: Spanish Ministry. (125.840,00 €)\
PI: Ramon Codina and Joan Baiges\
Reference: DPI2015-67857-R\
From 01/01/2016 to 31/12/2018\
Participation: 18/04/2017 to 22/09/2021

- **FORJACEMIC.** Investigación de nuevos procesos y aleaciones de aceros microaleados para la forja en caliente de cigüeñales de automoción. \
Funded by: CIE-GALFOR (Innterconecta) \
PI: Alfred Bermúdez \
From 22/10/2013 to 31/12/2014\
Participation: 01/09/2014 to 28/02/2015

### Private consulting

- **ENIPROGETTI.** Development of a mathematical and numerical model for the sensitivity analysis of the model of the physical channel to the material parameters and to the geometry of the perforation well. (2022)\
Founded by: ENI s.p.a. (50.000 €) \
Reference: 2500042110\
PI: Mario Putti.\

- Numerical analysis to estimate the optical quality degradation generated by the future European Solar Telescope (EST) over WHT (William Hershell Telescope) at Observatorio del Roque de Los Muchachos (ORM). (2020)\
PI: Ramon Codina and Joan Baiges.\
Participation: 01/03/2020 to 31/08/2020

- Proyecto de consultoría con el metro de Montreal, EWE+ para el diseño de pantallas ignífugas en el metro de Montreal. Numerical analysis to determine the aerodynamic loads on the tunnel Mont-Royal wall separation. (2020)\
PI: Ramon Codina and Joan Baiges.\
Participation: 01/03/2020 to 31/08/2020

## Membership of scientific societies

* Member of the Istituto Nazionale di Alta Matematica "Francesco Severi" (INDAM) - Gruppo Nazionale per il Calcolo Scientifico (GNCS), since 2023

* Member of the Spanish Association for Numerical Methods in Engineering (SEMNI), since 2018.

* Member of National Association of Mathematic’s Students (ANEM), since 2011.


## Participation on workshops

* *Kratos Workshop 2022*, in Deltares installations, Delft, Netherlands. [[Link](https://softwaredays.deltares.nl/-/kratos-workshop-2022-day-1)]\
Organized by [Deltares company](https://www.deltares.nl/en/). November 9-10, 2022

* *Numerical Analysis of protected systems*, in Geobrugg installations, Romanshorn, Switzerland.\
Organized by [Geobrugg company](https://www.geobrugg.com/en/Geobrugg-Safety-is-our-nature-114435.html). June 20-22, 2022.

* *Fortran Modernisation Workshop Programme* in Universitat Politècnica de Catalunya (UPC), BarcelonaTech, Spain. [[Link](http://aulas.cimne.com/vnews/10048/workshop---fortran-modernisation-workshop)]\
Organized by [NAG](https://www.nag.com/). July 24 - 26, 2017.
