---
title: "Research"
---


## Material Point Method

I am working on large deformation problems in structural mechanics. It is especially interesting because civil structures can suffer deformations, and even fractures, caused by strong impacts. I am using an enriched finite element based technique to solve this problem, called Material Point Method. My research focuses on the development and implementation of the Variational Multiscale Method to get stable formulations to deal with incompressible materials in solid and fluid mechanics problems.

## Computational fluid dynamics

### Numerical simulations of viscoelastic fluid flow with high elasticity

The global goal of my thesis was the development of mathematical models and numerical methods to simulate viscoelastic flows with high elasticity using the Finite Element Method. The equations that modelized the viscoelastic fluid flow present a large number of non-linearities and additionally, when the elasticity of the fluid is dominant respect to the convection forces, new instabilities must be treated. Reproducing it accurately is considered one of the biggest challenges in computational rheology, as classical methods fails to reproduce high elasticity levels.

### Other projects in fluid dynamics

#### Numerical analysis of the aerodynamic loads on a tunnel wall separation
In this project we study the influence of a telescope over another one concerning the optical parameters. To carry out the study, we solved the Navier Stokes equations on real terrain taking into account the temperature and considering the Smagorinsky model to capture the turbulence. And then we calculated the optical parameters that were influenced by the air temperature.

#### Numerical analysis of the optical quality over a telescope
Evaluation of the aerodynamic loads at the end of the constructed sections caused by the transient flows due to the train motion along the Mont-Royal tunnel. We carried out a CFD simulation using moving domains, where the geometry of the tunnel was fixed while the train was moving inside it. We used an arbitrary Lagrangian-Eulerian strategy, solving the Navier Stokes equations considering this motion.

## Other projects in computational mechanics

#### The numerical simulation of electromagnetic processes with hysteresis
The goal was the study and the numerical simulation of electromagnetic processes with hysteresis, with specific application on crankshafts. In this project I had to simulate the magnetisation process of the crankshafts and, subsequently, the demagnetisation process. This process is commonly used in automotive factories to detect fractures in crankshafts, using fluorescent metal shavings.

#### Numerical solver based on spectral methods
in order to reproduce the sound wave propagation in a well.