---
title: "Viscoelastic Flows"
format: html
---


### Numerical simulations of viscoelastic fluid flow with high elasticity

The overarching goal of my thesis was to develop mathematical models and numerical methods to simulate viscoelastic flows with high elasticity using the Finite Element Method. The equations modeling viscoelastic fluid flow present numerous nonlinearities. Additionally, when the elasticity of the fluid dominates over the convective forces, new instabilities must be addressed. Accurately reproducing these conditions is considered one of the biggest challenges in computational rheology, as classical methods fail to capture high levels of elasticity.

### Other projects in fluid dynamics


#### Numerical analysis of the optical quality over a telescope
In this project, we studied the influence of one telescope on another concerning optical parameters. To conduct the study, we solved the Navier-Stokes equations on real terrain, accounting for temperature and using the Smagorinsky model to capture turbulence. We then calculated the optical parameters influenced by the air temperature.

#### Numerical analysis of the aerodynamic loads on a tunnel wall separation
We evaluated the aerodynamic loads at the ends of constructed sections caused by transient flows due to train motion along the Mont-Royal tunnel. We conducted a CFD simulation using moving domains, where the tunnel geometry remained fixed while the train moved inside it. We employed an arbitrary Lagrangian-Eulerian strategy, solving the Navier-Stokes equations to account for this motion.



